// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjb_sTKFsUdRiD_Am4ewj6ODEZvsup7ng',
    appId: '1:476741072440:web:06da85ceafe25a16e758cd',
    messagingSenderId: '476741072440',
    projectId: 'crypto-master-app',
    authDomain: 'crypto-master-app.firebaseapp.com',
    storageBucket: 'crypto-master-app.appspot.com',
    measurementId: 'G-RJ8P8P6RT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_g0DmvGmxzfZuhy95Vgso6JD8_W2Lhps',
    appId: '1:476741072440:android:b6ab908ae301cfebe758cd',
    messagingSenderId: '476741072440',
    projectId: 'crypto-master-app',
    storageBucket: 'crypto-master-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPejii-_yf2X2HqGqAd4A35LLqMnCwK9w',
    appId: '1:476741072440:ios:1c2377f7e18cf0e9e758cd',
    messagingSenderId: '476741072440',
    projectId: 'crypto-master-app',
    storageBucket: 'crypto-master-app.appspot.com',
    iosBundleId: 'com.example.flutterAula1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPejii-_yf2X2HqGqAd4A35LLqMnCwK9w',
    appId: '1:476741072440:ios:5d08d98acba299ece758cd',
    messagingSenderId: '476741072440',
    projectId: 'crypto-master-app',
    storageBucket: 'crypto-master-app.appspot.com',
    iosBundleId: 'com.example.flutterAula1.RunnerTests',
  );
}
